"""Add Subscription model

Revision ID: 82910d49b515
Revises: 030690e99d25
Create Date: 2024-09-20 11:12:01.375897

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '82910d49b515'
down_revision = '030690e99d25'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Subscriptions',
    sa.Column('SubscriptionID', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('UserID', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('PlanName', sa.String(length=50), nullable=False),
    sa.Column('Amount', sa.Float(), nullable=False),
    sa.Column('StartDate', sa.DateTime(), nullable=False),
    sa.Column('EndDate', sa.DateTime(), nullable=False),
    sa.Column('Status', sa.String(length=20), nullable=False),
    sa.Column('LastPaymentDate', sa.DateTime(), nullable=False),
    sa.Column('PaymentReference', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['UserID'], ['Users.UserID'], ),
    sa.PrimaryKeyConstraint('SubscriptionID')
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Subscriptions')
    # ### end Alembic commands ###


def upgrade_operational():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_operational():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_audit():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_audit():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_archive():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_archive():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

