"""Archieve ChatMessages

Revision ID: 97c2a3461b8c
Revises: 3e5817940c17
Create Date: 2024-09-27 13:21:57.075661

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '97c2a3461b8c'
down_revision = '3e5817940c17'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_operational():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ChatMessage',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('insight_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=False),
    sa.Column('bot_response', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['insight_id'], ['Insights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('chat_messages')
    # ### end Alembic commands ###


def downgrade_operational():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=False),
    sa.Column('insight_id', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=False),
    sa.Column('user_message', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('bot_response', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['insight_id'], ['Insights.id'], name='FK__chat_mess__insig__47DBAE45'),
    sa.PrimaryKeyConstraint('id', name='PK__chat_mes__3213E83F3AFC314D')
    )
    op.drop_table('ChatMessage')
    # ### end Alembic commands ###


def upgrade_audit():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_audit():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_archive():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ArchivedChatMessage',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('insight_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=False),
    sa.Column('bot_response', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['insight_id'], ['ArchivedInsights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade_archive():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ArchivedChatMessage')
    # ### end Alembic commands ###

